/*
 * This source file was generated by the Gradle 'init' task
 */
package sh.jfm.springbootdemos.dependencyinjection.springbase;

public class App {
    private final GreetingService greetingService;

    public App() {
        this(new GreetingService());
    }

    public App(GreetingService greetingService) {
        this.greetingService = greetingService;
    }

    public String getGreeting() {
        return greetingService.greet("Spring World");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
