/*
 * This source file was generated by the Gradle 'init' task
 */
package sh.jfm.springbootdemos.dependencyinjection;

public class App {
    public static void main(String[] args) {
        System.out.println("Run tests to start Katas!");
    }
}
