/*
 * This source file was generated by the Gradle 'init' task
 */
package sh.jfm.springbootdemos.dependencyinjection;

public class App {
    public String getGreeting() {
        return "Hello Spring World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
